services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=testdb'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=testuser'
    ports:
      - 7000:5432
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
